param(
    [string]$OutFile = (Join-Path $PSScriptRoot 'skills\ps-edge\scripts\ps-edge.ps1')
)

$ErrorActionPreference = 'Stop'

function Add-PseBundleLine {
    param(
        [Parameter(Mandatory = $true)]
        [System.Text.StringBuilder]$Builder,

        [AllowNull()]
        [string]$Line = ''
    )

    [void]$Builder.Append($Line)
    [void]$Builder.Append("`r`n")
}

function Get-PseEntryPointTail {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    $lines = [System.IO.File]::ReadAllLines($Path)
    $insideRegion = $false
    $sawStart = $false
    $sawEnd = $false
    $outside = New-Object System.Collections.ArrayList

    foreach ($line in $lines) {
        if ($line -eq '#region PSE-SOURCES') {
            if ($insideRegion -or $sawStart) {
                throw "Invalid entry point: duplicate #region PSE-SOURCES marker in $Path"
            }
            $insideRegion = $true
            $sawStart = $true
            continue
        }

        if ($line -eq '#endregion PSE-SOURCES') {
            if (-not $insideRegion -or $sawEnd) {
                throw "Invalid entry point: unexpected #endregion PSE-SOURCES marker in $Path"
            }
            $insideRegion = $false
            $sawEnd = $true
            continue
        }

        if (-not $insideRegion) {
            [void]$outside.Add($line)
        }
    }

    if ($insideRegion -or -not $sawStart -or -not $sawEnd) {
        throw "Invalid entry point: missing PSE-SOURCES region markers in $Path"
    }

    return @($outside | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })
}

$repoRoot = $PSScriptRoot
$srcDir = Join-Path $repoRoot 'src'
$entryPoint = Join-Path $repoRoot 'ps-edge.ps1'
$srcFiles = @(Get-ChildItem -Path $srcDir -Filter '*.ps1' | Sort-Object Name)
if ($srcFiles.Count -eq 0) {
    throw "No source files found in $srcDir"
}

$outDir = Split-Path -Parent $OutFile
if (-not [string]::IsNullOrWhiteSpace($outDir) -and -not (Test-Path -LiteralPath $outDir)) {
    [void](New-Item -ItemType Directory -Path $outDir)
}

$builder = New-Object System.Text.StringBuilder
Add-PseBundleLine $builder '<#'
Add-PseBundleLine $builder 'ps-edge-cli'
Add-PseBundleLine $builder 'AI-friendly Microsoft Edge automation CLI in pure Windows PowerShell 5.1.'
Add-PseBundleLine $builder ''
Add-PseBundleLine $builder 'Generated by build.ps1 - do not edit directly.'
Add-PseBundleLine $builder ''
Add-PseBundleLine $builder 'Generation source list:'
foreach ($file in $srcFiles) {
    Add-PseBundleLine $builder ('- src/' + $file.Name)
}
Add-PseBundleLine $builder '- ps-edge.ps1 (outside #region PSE-SOURCES)'
Add-PseBundleLine $builder '#>'
Add-PseBundleLine $builder ''

foreach ($file in $srcFiles) {
    Add-PseBundleLine $builder ('# Source: src/' + $file.Name)
    $content = [System.IO.File]::ReadAllText($file.FullName)
    [void]$builder.Append($content.TrimEnd("`r", "`n"))
    Add-PseBundleLine $builder ''
    Add-PseBundleLine $builder ''
}

$tailLines = Get-PseEntryPointTail -Path $entryPoint
foreach ($line in $tailLines) {
    Add-PseBundleLine $builder $line
}

$encoding = New-Object System.Text.UTF8Encoding($true)
[System.IO.File]::WriteAllText($OutFile, $builder.ToString(), $encoding)

$item = Get-Item -LiteralPath $OutFile
Write-Host ("Wrote {0} ({1} bytes)" -f $item.FullName, $item.Length)

$skillDir = Join-Path $repoRoot 'skills\ps-edge'
$dogfoodDir = Join-Path $repoRoot '.claude\skills\ps-edge'
if (-not (Test-Path -LiteralPath $skillDir)) {
    throw "Skill directory not found: $skillDir"
}
if (-not (Test-Path -LiteralPath $dogfoodDir)) {
    [void](New-Item -ItemType Directory -Path $dogfoodDir)
}

$syncedCount = 0
$skillFiles = @(Get-ChildItem -LiteralPath $skillDir -Recurse -File | Sort-Object FullName)
foreach ($skillFile in $skillFiles) {
    $relativePath = $skillFile.FullName.Substring($skillDir.Length).TrimStart('\', '/')
    $targetPath = Join-Path $dogfoodDir $relativePath
    $targetDir = Split-Path -Parent $targetPath
    if (-not [string]::IsNullOrWhiteSpace($targetDir) -and -not (Test-Path -LiteralPath $targetDir)) {
        [void](New-Item -ItemType Directory -Path $targetDir)
    }
    Copy-Item -LiteralPath $skillFile.FullName -Destination $targetPath -Force
    $syncedCount++
}

Write-Host ("Synced {0} file(s) to {1}" -f $syncedCount, $dogfoodDir)
